apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: client
      protocol: TCP
      port: 4001
      targetPort: 4001